// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString, Default: "open"},
		{Name: "invite_code", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "owner_id", Type: field.TypeUUID},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:       "channels",
		Columns:    ChannelsColumns,
		PrimaryKey: []*schema.Column{ChannelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channels_users_owned_channels",
				Columns:    []*schema.Column{ChannelsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ChannelMembersColumns holds the columns for the "channel_members" table.
	ChannelMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "approved"}, Default: "approved"},
		{Name: "channel_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// ChannelMembersTable holds the schema information for the "channel_members" table.
	ChannelMembersTable = &schema.Table{
		Name:       "channel_members",
		Columns:    ChannelMembersColumns,
		PrimaryKey: []*schema.Column{ChannelMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_members_channels_memberships",
				Columns:    []*schema.Column{ChannelMembersColumns[3]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "channel_members_users_memberships",
				Columns:    []*schema.Column{ChannelMembersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ChannelMessagesColumns holds the columns for the "channel_messages" table.
	ChannelMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_name", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Nullable: true},
		{Name: "media_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "channel_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// ChannelMessagesTable holds the schema information for the "channel_messages" table.
	ChannelMessagesTable = &schema.Table{
		Name:       "channel_messages",
		Columns:    ChannelMessagesColumns,
		PrimaryKey: []*schema.Column{ChannelMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_messages_channels_messages",
				Columns:    []*schema.Column{ChannelMessagesColumns[5]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "channel_messages_users_channel_messages",
				Columns:    []*schema.Column{ChannelMessagesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChannelsTable,
		ChannelMembersTable,
		ChannelMessagesTable,
		UsersTable,
	}
)

func init() {
	ChannelsTable.ForeignKeys[0].RefTable = UsersTable
	ChannelMembersTable.ForeignKeys[0].RefTable = ChannelsTable
	ChannelMembersTable.ForeignKeys[1].RefTable = UsersTable
	ChannelMessagesTable.ForeignKeys[0].RefTable = ChannelsTable
	ChannelMessagesTable.ForeignKeys[1].RefTable = UsersTable
}
