// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// ChannelMember is the predicate function for channelmember builders.
type ChannelMember func(*sql.Selector)

// ChannelMessage is the predicate function for channelmessage builders.
type ChannelMessage func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
