# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Install dependencies first for better caching
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the auth-service binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /auth-service ./cmd/auth-service/main.go

# Final stage
FROM alpine:latest
WORKDIR /app

# Copy binary from builder
COPY --from=builder /auth-service /app/auth-service

# Expose port
EXPOSE 8080

CMD ["/app/auth-service"]
