// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/polyglot-chat/go-service/ent/channel"
	"github.com/polyglot-chat/go-service/ent/channelmessage"
	"github.com/polyglot-chat/go-service/ent/predicate"
	"github.com/polyglot-chat/go-service/ent/user"
)

// ChannelMessageUpdate is the builder for updating ChannelMessage entities.
type ChannelMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelMessageMutation
}

// Where appends a list predicates to the ChannelMessageUpdate builder.
func (_u *ChannelMessageUpdate) Where(ps ...predicate.ChannelMessage) *ChannelMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ChannelMessageUpdate) SetChannelID(v uuid.UUID) *ChannelMessageUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableChannelID(v *uuid.UUID) *ChannelMessageUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChannelMessageUpdate) SetUserID(v uuid.UUID) *ChannelMessageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableUserID(v *uuid.UUID) *ChannelMessageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *ChannelMessageUpdate) SetUserName(v string) *ChannelMessageUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableUserName(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *ChannelMessageUpdate) SetBody(v string) *ChannelMessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableBody(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *ChannelMessageUpdate) ClearBody() *ChannelMessageUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetMediaURL sets the "media_url" field.
func (_u *ChannelMessageUpdate) SetMediaURL(v string) *ChannelMessageUpdate {
	_u.mutation.SetMediaURL(v)
	return _u
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (_u *ChannelMessageUpdate) SetNillableMediaURL(v *string) *ChannelMessageUpdate {
	if v != nil {
		_u.SetMediaURL(*v)
	}
	return _u
}

// ClearMediaURL clears the value of the "media_url" field.
func (_u *ChannelMessageUpdate) ClearMediaURL() *ChannelMessageUpdate {
	_u.mutation.ClearMediaURL()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ChannelMessageUpdate) SetChannel(v *Channel) *ChannelMessageUpdate {
	return _u.SetChannelID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *ChannelMessageUpdate) SetAuthorID(id uuid.UUID) *ChannelMessageUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *ChannelMessageUpdate) SetAuthor(v *User) *ChannelMessageUpdate {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the ChannelMessageMutation object of the builder.
func (_u *ChannelMessageUpdate) Mutation() *ChannelMessageMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ChannelMessageUpdate) ClearChannel() *ChannelMessageUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *ChannelMessageUpdate) ClearAuthor() *ChannelMessageUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelMessageUpdate) check() error {
	if v, ok := _u.mutation.UserName(); ok {
		if err := channelmessage.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "ChannelMessage.user_name": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMessage.channel"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMessage.author"`)
	}
	return nil
}

func (_u *ChannelMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelmessage.Table, channelmessage.Columns, sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(channelmessage.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(channelmessage.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(channelmessage.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.MediaURL(); ok {
		_spec.SetField(channelmessage.FieldMediaURL, field.TypeString, value)
	}
	if _u.mutation.MediaURLCleared() {
		_spec.ClearField(channelmessage.FieldMediaURL, field.TypeString)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.ChannelTable,
			Columns: []string{channelmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.ChannelTable,
			Columns: []string{channelmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.AuthorTable,
			Columns: []string{channelmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.AuthorTable,
			Columns: []string{channelmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelMessageUpdateOne is the builder for updating a single ChannelMessage entity.
type ChannelMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelMessageMutation
}

// SetChannelID sets the "channel_id" field.
func (_u *ChannelMessageUpdateOne) SetChannelID(v uuid.UUID) *ChannelMessageUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableChannelID(v *uuid.UUID) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChannelMessageUpdateOne) SetUserID(v uuid.UUID) *ChannelMessageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableUserID(v *uuid.UUID) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *ChannelMessageUpdateOne) SetUserName(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableUserName(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *ChannelMessageUpdateOne) SetBody(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableBody(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *ChannelMessageUpdateOne) ClearBody() *ChannelMessageUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetMediaURL sets the "media_url" field.
func (_u *ChannelMessageUpdateOne) SetMediaURL(v string) *ChannelMessageUpdateOne {
	_u.mutation.SetMediaURL(v)
	return _u
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (_u *ChannelMessageUpdateOne) SetNillableMediaURL(v *string) *ChannelMessageUpdateOne {
	if v != nil {
		_u.SetMediaURL(*v)
	}
	return _u
}

// ClearMediaURL clears the value of the "media_url" field.
func (_u *ChannelMessageUpdateOne) ClearMediaURL() *ChannelMessageUpdateOne {
	_u.mutation.ClearMediaURL()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ChannelMessageUpdateOne) SetChannel(v *Channel) *ChannelMessageUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *ChannelMessageUpdateOne) SetAuthorID(id uuid.UUID) *ChannelMessageUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *ChannelMessageUpdateOne) SetAuthor(v *User) *ChannelMessageUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the ChannelMessageMutation object of the builder.
func (_u *ChannelMessageUpdateOne) Mutation() *ChannelMessageMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ChannelMessageUpdateOne) ClearChannel() *ChannelMessageUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *ChannelMessageUpdateOne) ClearAuthor() *ChannelMessageUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// Where appends a list predicates to the ChannelMessageUpdate builder.
func (_u *ChannelMessageUpdateOne) Where(ps ...predicate.ChannelMessage) *ChannelMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelMessageUpdateOne) Select(field string, fields ...string) *ChannelMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelMessage entity.
func (_u *ChannelMessageUpdateOne) Save(ctx context.Context) (*ChannelMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelMessageUpdateOne) SaveX(ctx context.Context) *ChannelMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelMessageUpdateOne) check() error {
	if v, ok := _u.mutation.UserName(); ok {
		if err := channelmessage.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "ChannelMessage.user_name": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMessage.channel"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMessage.author"`)
	}
	return nil
}

func (_u *ChannelMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChannelMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelmessage.Table, channelmessage.Columns, sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelmessage.FieldID)
		for _, f := range fields {
			if !channelmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(channelmessage.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(channelmessage.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(channelmessage.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.MediaURL(); ok {
		_spec.SetField(channelmessage.FieldMediaURL, field.TypeString, value)
	}
	if _u.mutation.MediaURLCleared() {
		_spec.ClearField(channelmessage.FieldMediaURL, field.TypeString)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.ChannelTable,
			Columns: []string{channelmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.ChannelTable,
			Columns: []string{channelmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.AuthorTable,
			Columns: []string{channelmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.AuthorTable,
			Columns: []string{channelmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChannelMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
