// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/polyglot-chat/go-service/ent/channel"
	"github.com/polyglot-chat/go-service/ent/channelmessage"
	"github.com/polyglot-chat/go-service/ent/user"
)

// ChannelMessageCreate is the builder for creating a ChannelMessage entity.
type ChannelMessageCreate struct {
	config
	mutation *ChannelMessageMutation
	hooks    []Hook
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelMessageCreate) SetChannelID(v uuid.UUID) *ChannelMessageCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChannelMessageCreate) SetUserID(v uuid.UUID) *ChannelMessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUserName sets the "user_name" field.
func (_c *ChannelMessageCreate) SetUserName(v string) *ChannelMessageCreate {
	_c.mutation.SetUserName(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *ChannelMessageCreate) SetBody(v string) *ChannelMessageCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableBody(v *string) *ChannelMessageCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetMediaURL sets the "media_url" field.
func (_c *ChannelMessageCreate) SetMediaURL(v string) *ChannelMessageCreate {
	_c.mutation.SetMediaURL(v)
	return _c
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableMediaURL(v *string) *ChannelMessageCreate {
	if v != nil {
		_c.SetMediaURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelMessageCreate) SetCreatedAt(v time.Time) *ChannelMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableCreatedAt(v *time.Time) *ChannelMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelMessageCreate) SetID(v uuid.UUID) *ChannelMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableID(v *uuid.UUID) *ChannelMessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelMessageCreate) SetChannel(v *Channel) *ChannelMessageCreate {
	return _c.SetChannelID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_c *ChannelMessageCreate) SetAuthorID(id uuid.UUID) *ChannelMessageCreate {
	_c.mutation.SetAuthorID(id)
	return _c
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *ChannelMessageCreate) SetAuthor(v *User) *ChannelMessageCreate {
	return _c.SetAuthorID(v.ID)
}

// Mutation returns the ChannelMessageMutation object of the builder.
func (_c *ChannelMessageCreate) Mutation() *ChannelMessageMutation {
	return _c.mutation
}

// Save creates the ChannelMessage in the database.
func (_c *ChannelMessageCreate) Save(ctx context.Context) (*ChannelMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelMessageCreate) SaveX(ctx context.Context) *ChannelMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := channelmessage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelMessageCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelMessage.channel_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChannelMessage.user_id"`)}
	}
	if _, ok := _c.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`ent: missing required field "ChannelMessage.user_name"`)}
	}
	if v, ok := _c.mutation.UserName(); ok {
		if err := channelmessage.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "ChannelMessage.user_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelMessage.created_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelMessage.channel"`)}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required edge "ChannelMessage.author"`)}
	}
	return nil
}

func (_c *ChannelMessageCreate) sqlSave(ctx context.Context) (*ChannelMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelMessageCreate) createSpec() (*ChannelMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelmessage.Table, sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserName(); ok {
		_spec.SetField(channelmessage.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(channelmessage.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.MediaURL(); ok {
		_spec.SetField(channelmessage.FieldMediaURL, field.TypeString, value)
		_node.MediaURL = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.ChannelTable,
			Columns: []string{channelmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.AuthorTable,
			Columns: []string{channelmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelMessageCreateBulk is the builder for creating many ChannelMessage entities in bulk.
type ChannelMessageCreateBulk struct {
	config
	err      error
	builders []*ChannelMessageCreate
}

// Save creates the ChannelMessage entities in the database.
func (_c *ChannelMessageCreateBulk) Save(ctx context.Context) ([]*ChannelMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelMessageCreateBulk) SaveX(ctx context.Context) []*ChannelMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
