// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/polyglot-chat/go-service/ent/channel"
	"github.com/polyglot-chat/go-service/ent/channelmember"
	"github.com/polyglot-chat/go-service/ent/channelmessage"
	"github.com/polyglot-chat/go-service/ent/schema"
	"github.com/polyglot-chat/go-service/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescName is the schema descriptor for name field.
	channelDescName := channelFields[1].Descriptor()
	// channel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	channel.NameValidator = channelDescName.Validators[0].(func(string) error)
	// channelDescType is the schema descriptor for type field.
	channelDescType := channelFields[2].Descriptor()
	// channel.DefaultType holds the default value on creation for the type field.
	channel.DefaultType = channelDescType.Default.(string)
	// channelDescInviteCode is the schema descriptor for invite_code field.
	channelDescInviteCode := channelFields[3].Descriptor()
	// channel.InviteCodeValidator is a validator for the "invite_code" field. It is called by the builders before save.
	channel.InviteCodeValidator = channelDescInviteCode.Validators[0].(func(string) error)
	// channelDescCreatedAt is the schema descriptor for created_at field.
	channelDescCreatedAt := channelFields[5].Descriptor()
	// channel.DefaultCreatedAt holds the default value on creation for the created_at field.
	channel.DefaultCreatedAt = channelDescCreatedAt.Default.(func() time.Time)
	// channelDescID is the schema descriptor for id field.
	channelDescID := channelFields[0].Descriptor()
	// channel.DefaultID holds the default value on creation for the id field.
	channel.DefaultID = channelDescID.Default.(func() uuid.UUID)
	channelmemberFields := schema.ChannelMember{}.Fields()
	_ = channelmemberFields
	// channelmemberDescJoinedAt is the schema descriptor for joined_at field.
	channelmemberDescJoinedAt := channelmemberFields[3].Descriptor()
	// channelmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	channelmember.DefaultJoinedAt = channelmemberDescJoinedAt.Default.(func() time.Time)
	// channelmemberDescID is the schema descriptor for id field.
	channelmemberDescID := channelmemberFields[0].Descriptor()
	// channelmember.DefaultID holds the default value on creation for the id field.
	channelmember.DefaultID = channelmemberDescID.Default.(func() uuid.UUID)
	channelmessageFields := schema.ChannelMessage{}.Fields()
	_ = channelmessageFields
	// channelmessageDescUserName is the schema descriptor for user_name field.
	channelmessageDescUserName := channelmessageFields[3].Descriptor()
	// channelmessage.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	channelmessage.UserNameValidator = channelmessageDescUserName.Validators[0].(func(string) error)
	// channelmessageDescCreatedAt is the schema descriptor for created_at field.
	channelmessageDescCreatedAt := channelmessageFields[6].Descriptor()
	// channelmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	channelmessage.DefaultCreatedAt = channelmessageDescCreatedAt.Default.(func() time.Time)
	// channelmessageDescID is the schema descriptor for id field.
	channelmessageDescID := channelmessageFields[0].Descriptor()
	// channelmessage.DefaultID holds the default value on creation for the id field.
	channelmessage.DefaultID = channelmessageDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
